local library = require(game.StarterGui.script)

local window = library:new({})

local page1 = window:page({})
local sec = page1:section({})

sec:button({callback = function(v)
	window:notification({text = "clicked button"})
end})
local t1 = sec:toggle({callback = function(v)
	window:notification({text = "changed toggle: "..tostring(v)})
end})
local t2 = sec:slider({callback = function(v)
	window:notification({text = "changed slider: "..tostring(v)})
end})
local t3 = sec:dropdown({def = "1",options = {"1","2","3","5","6","7"},callback = function(v)
	window:notification({text = "changed dropdown: "..tostring(v)})
end})
local t4 = sec:multibox({def = {"1"},options = {"1","2","3","5","6","7"},callback = function(v)
	print(v)
end})
local t5 = sec:colorpicker({callback = function(v)
	window:notification({text = "changed color: "..tostring(v)})
end})
local t6 = sec:textbox({callback = function(v)
	window:notification({text = "changed textbot: "..tostring(v)})
end})
sec:button({name = "reset",callback = function()
	t1:set(false)
	t2:set(50)
	t3:set("1")
	t4:set({"1","2"})
	t5:set(Color3.new(1,0,0))
	t6:set("Hello !")
end})
